version: '3.7'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    image: lightshield/proxy:${TAG}
    container_name: lightshield_proxy
    env_file:
      - secrets.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      default:
        aliases:
          - proxy
    ports:
      - 8888:8000

  proxy_sync:
    image: redis:6.0
    command: ["redis-server", "--appendonly", "yes" ]
    networks:
      default:
        aliases:
          - proxy_sync
    restart: always
    volumes:
      - ./lua_scripts:/lua_scripts/
    environment:
      - "LOG_LEVEL=debug"
    ports:
      - 6379:6379


networks:
  default:
    external:
      name: lightshield
