version: '3.7'
services:


  nginx:
    image: nginx:1.19.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      default:
        aliases:
          - lightshield_proxy

  proxy_na1:
    build:
      dockerfile: Dockerfile
      context: .
    image: lightshield_proxy_na1
    container_name: lightshield_proxy_na1
    environment:
      - SERVER=NA1
    env_file:
      - secrets.env
    restart: always
    volumes:
      - /logs/lightshield_proxy/:/logs/
      - ./configs/:/project/configs/
    networks:
      default:
        aliases:
          - lightshield_proxy_na1
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"


  proxy_euw1:
    image: lightshield_proxy_na1
    container_name: lightshield_proxy_euw1
    environment:
      - SERVER=EUW1
    env_file:
      - secrets.env
    restart: always
    volumes:
      - /logs/lightshield_proxy/:/logs/
      - ./configs/:/project/configs/
    networks:
      default:
        aliases:
          - lightshield_proxy_euw1
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

  proxy_kr:
    image: lightshield_proxy_na1
    container_name: lightshield_proxy_kr
    environment:
      - SERVER=KR
    env_file:
      - secrets.env
    restart: always
    volumes:
      - /logs/lightshield_proxy/:/logs/
      - ./configs/:/project/configs/
    networks:
      default:
        aliases:
          - lightshield_proxy_kr
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

networks:
  default:
    external:
      name: lightshield
