version: '3.7'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    image: lightshield/proxy:${TAG}
    container_name: lightshield_proxy
    env_file:
      - secrets.env
    restart: always
    networks:
      aliases:
        - proxy
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

networks:
  default:
    external:
      name: lightshield
