version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_proxy
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/
        - ./configs/:/project/configs/
