version: '3.7'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: lightshield_proxy_${SERVER}
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
      - /logs/lightshield_proxy/:/logs/
      - ./configs/:/project/configs/
    networks:
      default:
        aliases:
          - lightshield_proxy_${SERVER}
    logging:
      driver: "json-file"
      options:
       max-file: "5"
       max-size: "10m"

networks:
  default:
    external:
      name: lightshield
