version: '2.3'
services:

  proxy:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: lightshield_proxy_${SERVER}
    environment:
      - SERVER=${SERVER}
    env_file:
      - secrets.env
    restart: always
    volumes:
        - ./logs/:/project/logs/
        - ./configs/:/project/configs/


networks:
  default:
    external:
      name: lightshield
